rvm:
- 2.2
node_js:
- '8'
install:
- bundle install
- npm install
script:
- npm test
deploy:
  tag: next
  provider: npm
  email: tina.umlandt@gmail.com
  api_key:
    secure: 04W5ymOr3usbzAQEw1Fl1QiudJ9j1HQ0cFgWnxqbUMAtI7dZPo635nM5/0jiJdLwc7x4hTXBPtmo8y5IujzfgRN4d4mcG2QZ2+4wiI5nExYZhF6xS0YheWpPYn9E5uG5FomBbwsLPEDo6eW1fYTs71bxCfi5s+WDWw+bSjkmDVJNqmAc5A7S9dZFPkaDbofGqnk5ubJZG4VjjJtNqo+1N9XINysIavmmhEuN1pd+jwTlcg9MkmpLI2N+6uigHS3AClwE70UBpA4p21Hfy0OmdPghXLN+jOnl69CyAUsNtQ/knEp3Tc7VVHOXvo+9RPHGRf8xN4HJVAnH3Kt9LBeh/HCvUo0aecRDzL/C3kRmt9fyrlNtligm+b40e677jiqnP3RPv1vkVAhRuw3+ib+OT+1dE/F7F3dSUyKcPnzkgAJ7HO/kP2eJlw/me6jBuPMTKS3pbDtlpgrfpAi8SUoDmN3wh7kv//feabSKhql63ddhUCUhw2QmsEwZ3soA9+qqZzqdeX7ZBLlT1GkCHlUt9CPGAAEmLsDzPvwSCB86JqIqTq/vufxEOghLA0QioH3W+aobermvAeY/mBIDJ39M33zbLw5znWJfXTeXCxwFckS2MAXMdPIwwfr7B2EAylohPGwWId8WzohWvuarJozeELzvHuF1rNKqRKYVQtnpHk0=
  on:
    tags: true
    repo: klyrr/krokus
    branch: master
